#!/bin/sh

echo
echo "Setting hostname..."
set -x
hostname -F /etc/hostname
set +x

echo
echo "Setting up networking..."
interfaces=$(awk '$1 == "auto" {for (i = 2; i <= NF; i = i + 1) printf("%s ", $i)}' /etc/network/interfaces)

for interface in $interfaces; do
	echo
	echo "Bringing up $interface interface..."
	set -x
	ifup $interface
	set +x
done
