#!/bin/sh

echo
echo 'Welcome to                      '
echo ' _______           ____   _____ '
echo '|__   __|         / __ \ / ____|'
echo '   | | __ _ _   _| |  | | (___  '
echo '   | |/ _` | | | | |  | |\___ \ '
echo '   | | (_| | |_| | |__| |____) |'
echo '   |_|\__,_|\__, |\____/|_____/ '
echo '             __/ |              '
echo '            |___/               '
echo

echo
echo "Setting up basic mounts"
set -x
mkdir -p /proc /sys /dev
mount -t proc -o noexec,nosuid,nodev proc /proc
mount -t sysfs -o noexec,nosuid,nodev sysfs /sys
mount -t devtmpfs -o exec,nosuid,mode=0755,size=2M devtmpfs /dev
mkdir -p /dev/pts /dev/shm
mount -t devpts -o gid=5,mode=0620,noexec,nosuid devpts /dev/pts
mount -t tmpfs -o nodev,nosuid,noexec shm /dev/shm
mkdir -p /tmp /run
set +x

echo
echo "We're done! Now starting the init daemon:"
set -x
exec /sbin/init
set +x

echo "If you see me, something terrible went wrong with the init daemon"
